SELECT bool_and(customer_username IN (SELECT pays.customer_username FROM pays INNER JOIN event ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location AND event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND event.event_active) OR customer_username IN (SELECT distinct is_a.customer_username FROM is_a INNER JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location AND event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND event.event_active)) FROM customer WHERE customer_username = 'rapol'

select distinct is_a.customer_username, event.event_name, event.event_start_date, event.event_location from is_a inner join event on is_a.event_name = event.event_name and is_a.event_start_date = event.event_start_date and is_a.event_location = event.event_location;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a join event on is_a.event_name = event.event_name and is_a.event_start_date = event.event_start_date and is_a.event_location = event.event_location join pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location join hosts on hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location join belongs_to on belongs_to.organization_name = hosts.organization_name join customer on customer.customer_username = pays.customer_username or customer.customer_username = is_a.customer_username or customer.customer_username = event.customer_username or customer.customer_username = belongs_to.customer_username where event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'test02' and event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username OR customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username where event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active

-- Get event_pk
SELECT event_name, event_start_date, event_location, customer_username FROM event;

-- vvvvvvv Check if Event Organizer (for regular Events) [Not really needed]
SELECT distinct customer.customer_username FROM customer JOIN event ON customer.customer_username = event.customer_username WHERE event.event_name = 'Event 02' AND event.event_start_date = '2015-05-05 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'rapol' AND event.event_active;

SELECT distinct customer.customer_username FROM customer JOIN event ON customer.customer_username = event.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;
-- ^^^^^^^ Check if Event Organizer (for regular Events) [Not really needed]

-- vvvvvvv Check if Event Organizer (For every type of Event)
SELECT distinct customer.customer_username FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location LEFT OUTER JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND customer.customer_username = 'papaluisre' AND event.event_active;

SELECT distinct customer.customer_username FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location LEFT OUTER JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;
-- ^^^^^^^ Check if Event Organizer (For every type of Event)

-- vvvvvvv Check if Event Organizer (for hosted Events)
SELECT distinct customer.customer_username FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND event.event_active;

SELECT distinct customer.customer_username FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;

SELECT distinct customer.customer_username FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25T13:00:00.000Z' AND event.event_location = 'miradero' AND customer.customer_username = 'ollidab' AND event.event_active;
-- ^^^^^^^ Check if Event Organizer (for hosted Events)

-- Get meetup_pk and creator username
SELECT event_name, event_start_date, event_location, meetup_location, meetup_start_date, customer_username FROM meetup;

-- vvvvvvv Check if can delete Meetup
SELECT distinct customer.customer_username FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location join hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username OR customer.customer_username = meetup.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'rapol' AND meetup.customer_username = 'ollidab' AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;

SELECT distinct customer.customer_username FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location join hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username OR customer.customer_username = meetup.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND meetup.customer_username = $5 AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;
-- ^^^^^^^ Check if can delete Meetup

-- vvvvvvv Check if Spectator/Competitors/Organizers (for hosted Events)
SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username OR customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username OR customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;
-- ^^^^^^^ Check if Spectator/Competitors/Organizers (for hosted Events)

-- vvvvvvv Check if can write Review (Spectator/Competitors) (for hosted Events)
SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'test01' AND event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 -- List of all who can write reviews for a given event
 AND customer.customer_username = $4 AND event.event_active; -- Check if I'm on the list
-- ^^^^^^^ Check if Spectator/Competitors/Organizers (for hosted Events)

-- vvvvvvv Check if your Review
SELECT distinct customer.customer_username FROM review JOIN event ON review.event_name = event.event_name AND review.event_start_date = event.event_start_date AND review.event_location = event.event_location JOIN customer ON customer.customer_username = review.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND review.customer_username = 'ollidab' AND event.event_active;

SELECT distinct customer.customer_username FROM review JOIN event ON review.event_name = event.event_name AND review.event_start_date = event.event_start_date AND review.event_location = event.event_location JOIN customer ON customer.customer_username = review.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND review.customer_username = $5 AND event.event_active;
-- ^^^^^^^ Check if your Review

-- vvvvvvv Check if your Meetup
SELECT distinct customer.customer_username FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location JOIN customer ON customer.customer_username = meetup.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND meetup.customer_username = 'ollidab' AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location JOIN customer ON customer.customer_username = meetup.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND meetup.customer_username = $5 AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;
-- ^^^^^^^ Check if your Meetup

-- vvvvvvv Get competitors info
SELECT distinct customer.customer_username, customer.customer_first_name, customer.customer_last_name, customer.customer_tag, customer.customer_profile_pic, tournament.competitor_fee FROM event JOIN is_a ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN tournament ON tournament.event_name = event.event_name AND tournament.event_start_date = event.event_start_date AND tournament.event_location = event.event_location AND is_a.tournament_name = tournament.tournament_name JOIN customer ON customer.customer_username = is_a.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero';
-- ^^^^^^^ Get competitors info

-- vvvvvvv Get spectators info
SELECT distinct customer.customer_username, customer.customer_first_name, customer.customer_last_name, customer.customer_tag, customer.customer_profile_pic, pays.spec_fee_name FROM event JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN customer ON customer.customer_username = pays.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero';
-- ^^^^^^^ Get spectators info

 select news_number, news_title, news_content, news_date_posted, bool_and(news_number IN (SELECT news.news_number FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username JOIN news ON news.event_name = event.event_name AND news.event_start_date = event.event_start_date AND news.event_location = event.event_location WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND event.event_active)) AS can_edit from news GROUP BY news_number, news_title, news_content, news_date_posted;

SELECT distinct customer.customer_username FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location LEFT OUTER JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND event.event_active;

SELECT event.event_name, event.event_start_date, event.event_end_date, event.event_location, event.event_venue, event.event_banner, event.event_logo, event.event_end_date, event.event_registration_deadline, event.event_rules, event.event_description, event.event_deduction_fee, event.event_is_online, event.event_type, bool_and(concat(event.event_name, event.event_location, event.event_start_date) IN (SELECT concat(event.event_name, event.event_location, event.event_start_date) FROM hosts)) as is_hosted FROM event WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND event_active GROUP BY event_name, event_start_date, event_location;

SELECT event.event_name, event.event_start_date, event.event_end_date, event.event_location, event.event_venue, event.event_banner, event.event_logo, event.event_end_date, event.event_registration_deadline, event.event_rules, event.event_description, event.event_deduction_fee, event.event_is_online, event.event_type, event.customer_username AS creator, hosts.organization_name AS host FROM event JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location WHERE event_name = $1 AND event_start_date = $2 AND event_location = $3 AND event_active GROUP BY event_name, event_start_date, event_location

-- vvvvvvv New query for event info
SELECT event.event_name, event.event_start_date, event.event_end_date, event.event_location, event.event_venue, event.event_banner, event.event_logo, event.event_registration_deadline, event.event_rules, event.event_description, event.event_deduction_fee, event.event_is_online, event.event_type, event.customer_username AS creator, hosts.organization_name AS host FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location WHERE event.event_name = 'Event 05' AND event.event_start_date = '2025-11-19 09:00:00' AND event.event_location = 'Calle Bosque, Mayaguez, PR 00681-9042' AND event.event_active;
-- ^^^^^^^ New query for event info

SELECT event.event_name, event.event_start_date, event.event_end_date, event.event_location, event.event_logo, event.event_end_date, event.event_registration_deadline, event.event_rules, event.event_description, event.event_deduction_fee, event.event_is_online, event.event_type, bool_and(concat(event.event_name, event.event_location, event.event_start_date) IN (SELECT concat(event.event_name, event.event_location, event.event_start_date) FROM hosts)) as is_hosted FROM event WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND event_active GROUP BY event_name, event_start_date, event_location;

select is_set.event_name, is_set.event_start_date, is_set.event_location, is_set.tournament_name, is_set.round_number, is_set.round_of, is_set.match_number, is_set.set_seq, (submits.score IS NULL) as can_submit from is_set LEFT OUTER JOIN submits ON is_set.event_name = submits.event_name AND is_set.event_start_date = submits.event_start_date AND is_set.event_location = submits.event_location AND is_set.tournament_name = submits.tournament_name AND is_set.round_number = submits.round_number AND is_set.round_of = submits.round_of AND is_set.match_number = submits.match_number AND is_set.set_seq = submits.set_seq where is_set.tournament_name = 'Mortal Kombat X Qualifiers';

select is_set.event_name, is_set.event_start_date, is_set.event_location, is_set.tournament_name, is_set.round_number, is_set.round_of, is_set.match_number, is_set.set_seq, (submits.score IS NULL) as can_submit from is_set JOIN competes ON is_set.event_name = competes.event_name AND is_set.event_start_date = competes.event_start_date AND is_set.event_location = competes.event_location AND is_set.tournament_name = competes.tournament_name AND is_set.round_number = competes.round_number AND is_set.round_of = competes.round_of AND is_set.match_number = competes.match_number LEFT OUTER JOIN submits ON is_set.event_name = submits.event_name AND is_set.event_start_date = submits.event_start_date AND is_set.event_location = submits.event_location AND is_set.tournament_name = submits.tournament_name AND is_set.round_number = submits.round_number AND is_set.round_of = submits.round_of AND is_set.match_number = submits.match_number AND is_set.set_seq = submits.set_seq where is_set.tournament_name = 'Mortal Kombat X Qualifiers';

-- vvvvvvv Get the sets for a match where a user is scheduled to play
SELECT is_set.event_name, is_set.event_start_date, is_set.event_location, is_set.tournament_name, is_set.round_number, is_set.round_of, is_set.match_number, is_set.set_seq, competes.competitor_number, (submits.score IS NULL AND NOT is_set.set_completed) AS can_submit_score FROM is_set JOIN competes ON is_set.event_name = competes.event_name AND is_set.event_start_date = competes.event_start_date AND is_set.event_location = competes.event_location AND is_set.tournament_name = competes.tournament_name AND is_set.round_number = competes.round_number AND is_set.round_of = competes.round_of AND is_set.match_number = competes.match_number JOIN is_a ON is_a.event_name = competes.event_name AND is_a.event_start_date = competes.event_start_date AND is_a.event_location = competes.event_location AND is_a.tournament_name = competes.tournament_name AND is_a.competitor_number = competes.competitor_number LEFT OUTER JOIN submits ON submits.event_name = competes.event_name AND submits.event_start_date = competes.event_start_date AND submits.event_location = competes.event_location AND submits.tournament_name = competes.tournament_name AND submits.competitor_number = competes.competitor_number AND submits.round_number = competes.round_number AND submits.round_of = competes.round_of AND submits.match_number = competes.match_number AND submits.set_seq = is_set.set_seq WHERE is_set.event_name = 'Event 01' AND is_set.event_start_date = '2015-03-25 09:00:00' AND is_set.event_location = 'miradero' AND is_set.tournament_name = 'Mortal Kombat X Qualifiers' AND is_set.round_number = 1 AND is_set.round_of = 'Group' AND is_set.match_number = 1 AND is_a.customer_username = 'rapol';
-- ^^^^^^^ Get the sets for a match where a user is scheduled to play

-- vvvvvvv Get my matchups
-- Past matchups
SELECT match.event_name, match.event_start_date, match.event_location, match.tournament_name, match.round_number, match.round_of, match.match_number, tournament.is_team_based FROM match JOIN competes ON match.event_name = competes.event_name AND match.event_start_date = competes.event_start_date AND match.event_location = competes.event_location AND match.tournament_name = competes.tournament_name AND match.round_number = competes.round_number AND match.round_of = competes.round_of AND match.match_number = competes.match_number JOIN is_a ON is_a.event_name = competes.event_name AND is_a.event_start_date = competes.event_start_date AND is_a.event_location = competes.event_location AND is_a.tournament_name = competes.tournament_name AND is_a.competitor_number = competes.competitor_number JOIN tournament ON match.event_name = tournament.event_name AND match.event_start_date = tournament.event_start_date AND match.event_location = tournament.event_location AND match.tournament_name = tournament.tournament_name WHERE is_a.customer_username = 'rapol' AND match.match_completed;

-- Current matchups
SELECT match.event_name, match.event_start_date, match.event_location, match.tournament_name, match.round_number, match.round_of, match.match_number, tournament.is_team_based FROM match JOIN competes ON match.event_name = competes.event_name AND match.event_start_date = competes.event_start_date AND match.event_location = competes.event_location AND match.tournament_name = competes.tournament_name AND match.round_number = competes.round_number AND match.round_of = competes.round_of AND match.match_number = competes.match_number JOIN is_a ON is_a.event_name = competes.event_name AND is_a.event_start_date = competes.event_start_date AND is_a.event_location = competes.event_location AND is_a.tournament_name = competes.tournament_name AND is_a.competitor_number = competes.competitor_number JOIN tournament ON match.event_name = tournament.event_name AND match.event_start_date = tournament.event_start_date AND match.event_location = tournament.event_location AND match.tournament_name = tournament.tournament_name WHERE is_a.customer_username = 'papaluisre' AND NOT match.match_completed;

-- if not team_based
SELECT customer.customer_tag, customer.customer_profile_pic, sum(submits.score) FROM customer JOIN is_a ON is_a.customer_username = customer.customer_username JOIN competes ON is_a.event_name = competes.event_name AND is_a.event_start_date = competes.event_start_date AND is_a.event_location = competes.event_location AND is_a.tournament_name = competes.tournament_name AND is_a.competitor_number = competes.competitor_number LEFT OUTER JOIN submits ON submits.event_name = competes.event_name AND submits.event_start_date = competes.event_start_date AND submits.event_location = competes.event_location AND submits.tournament_name = competes.tournament_name AND submits.competitor_number = competes.competitor_number AND submits.round_number = competes.round_number AND submits.round_of = competes.round_of AND submits.match_number = competes.match_number WHERE competes.event_name = 'Event 01' AND competes.event_start_date = '2015-03-25 09:00:00' AND competes.event_location = 'miradero' AND competes.tournament_name = 'Mortal Kombat X Qualifiers' AND competes.round_number = 1 AND competes.round_of = 'Group' AND competes.match_number = 1 GROUP BY customer.customer_tag, customer.customer_profile_pic;

-- else
SELECT team.team_name, team.team_logo, sum(submits.score) FROM team JOIN competes_for ON competes_for.team_name = team.team_name JOIN competes ON competes_for.event_name = competes.event_name AND competes_for.event_start_date = competes.event_start_date AND competes_for.event_location = competes.event_location AND competes_for.tournament_name = competes.tournament_name AND competes_for.competitor_number = competes.competitor_number LEFT OUTER JOIN submits ON submits.event_name = competes.event_name AND submits.event_start_date = competes.event_start_date AND submits.event_location = competes.event_location AND submits.tournament_name = competes.tournament_name AND submits.competitor_number = competes.competitor_number AND submits.round_number = competes.round_number AND submits.round_of = competes.round_of AND submits.match_number = competes.match_number WHERE competes.event_name = 'Event 01' AND competes.event_start_date = '2015-03-25 09:00:00' AND competes.event_location = 'miradero' AND competes.tournament_name = 'Mortal Kombat X Qualifiers' AND competes.round_number = 1 AND competes.round_of = 'Group' AND competes.match_number = 1 GROUP BY team.team_name, team.team_logo;
-- ^^^^^^^ Get my matchups

-- vvvvvvv Check if a user can submit score
SELECT is_a.competitor_number FROM customer JOIN is_a ON is_a.customer_username = customer.customer_username JOIN competes ON is_a.event_name = competes.event_name AND is_a.event_start_date = competes.event_start_date AND is_a.event_location = competes.event_location AND is_a.tournament_name = competes.tournament_name AND is_a.competitor_number = competes.competitor_number LEFT OUTER JOIN submits ON submits.event_name = competes.event_name AND submits.event_start_date = competes.event_start_date AND submits.event_location = competes.event_location AND submits.tournament_name = competes.tournament_name AND submits.competitor_number = competes.competitor_number AND submits.round_number = competes.round_number AND submits.round_of = competes.round_of AND submits.match_number = competes.match_number WHERE competes.event_name = 'Event 01' AND competes.event_start_date = '2015-03-25 09:00:00' AND competes.event_location = 'miradero' AND competes.tournament_name = 'Mortal Kombat X Qualifiers' AND competes.round_number = 1 AND competes.round_of = 'Group' AND competes.match_number = 1  AND customer.customer_username = 'ollidab' GROUP BY is_a.competitor_number;
-- ^^^^^^^ Check if a user can submit score