START TRANSACTION;

INSERT INTO meetup (event_name, event_start_date, event_location, meetup_location, meetup_name, meetup_start_date, meetup_end_date, meetup_description, customer_username) VALUES ('Event 01', '2015-03-25 09:00:00', 'miradero', 'Room 301, Mayaguez Resort and Casino, Mayaguez, Puerto Rico', 'Project X', '2015-03-24 13:00:00', '2015-03-24 22:05:06', 'Practice Matches for the tournament tomorrow hosted by the Puertorican Team', 'papaluisre');


INSERT INTO "to_play" (event_name, event_start_date, event_location, meetup_location, meetup_start_date, game_name)
VALUES ('Event 01', '2015-03-25 09:00:00', 'University of Puerto Rico at Mayaguez, Mayaguez, PR 00681-9042', 'Room 301, Mayaguez Resort and Casino, Mayaguez, Puerto Rico', '2015-03-24 13:00:00', 'Super Smash Bros. Melee');

COMMIT;

SELECT bool_and(customer_username IN (SELECT pays.customer_username FROM pays INNER JOIN event ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location AND event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND event.event_active) OR customer_username IN (SELECT distinct is_a.customer_username FROM is_a INNER JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location AND event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND event.event_active)) FROM customer WHERE customer_username = 'rapol'

select distinct is_a.customer_username, event.event_name, event.event_start_date, event.event_location from is_a inner join event on is_a.event_name = event.event_name and is_a.event_start_date = event.event_start_date and is_a.event_location = event.event_location;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a join event on is_a.event_name = event.event_name and is_a.event_start_date = event.event_start_date and is_a.event_location = event.event_location join pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location join hosts on hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location join belongs_to on belongs_to.organization_name = hosts.organization_name join customer on customer.customer_username = pays.customer_username or customer.customer_username = is_a.customer_username or customer.customer_username = event.customer_username or customer.customer_username = belongs_to.customer_username where event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'test02' and event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username OR customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username where event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active

-- Get event_pk
SELECT event_name, event_start_date, event_location, customer_username FROM event;

-- vvvvvvv Check if Event Organizer (for regular Events) [Not really needed]
SELECT distinct customer.customer_username FROM customer JOIN event ON customer.customer_username = event.customer_username WHERE event.event_name = 'Event 02' AND event.event_start_date = '2015-05-05 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'rapol' AND event.event_active;

SELECT distinct customer.customer_username FROM customer JOIN event ON customer.customer_username = event.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;
-- ^^^^^^^ Check if Event Organizer (for regular Events) [Not really needed]

-- vvvvvvv Check if Event Organizer (For every type of Event)
SELECT distinct customer.customer_username FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location LEFT OUTER JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND customer.customer_username = 'papaluisre' AND event.event_active;

SELECT distinct customer.customer_username FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location LEFT OUTER JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;
-- ^^^^^^^ Check if Event Organizer (For every type of Event)

-- vvvvvvv Check if Event Organizer (for hosted Events)
SELECT distinct customer.customer_username FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND event.event_active;

SELECT distinct customer.customer_username FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;

SELECT distinct customer.customer_username FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25T13:00:00.000Z' AND event.event_location = 'miradero' AND customer.customer_username = 'ollidab' AND event.event_active;
-- ^^^^^^^ Check if Event Organizer (for hosted Events)

-- Get meetup_pk and creator username
SELECT event_name, event_start_date, event_location, meetup_location, meetup_start_date, customer_username FROM meetup;

-- vvvvvvv Check if can delete Meetup
SELECT distinct customer.customer_username FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location join hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username OR customer.customer_username = meetup.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'rapol' AND meetup.customer_username = 'ollidab' AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;

SELECT distinct customer.customer_username FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location join hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username OR customer.customer_username = meetup.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND meetup.customer_username = $5 AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;
-- ^^^^^^^ Check if can delete Meetup

-- vvvvvvv Check if Spectator/Competitors/Organizers (for hosted Events)
SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username OR customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username OR customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND event.event_active;
-- ^^^^^^^ Check if Spectator/Competitors/Organizers (for hosted Events)

-- vvvvvvv Check if can write Review (Spectator/Competitors) (for hosted Events)
SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'test01' AND event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM is_a JOIN event ON is_a.event_name = event.event_name AND is_a.event_start_date = event.event_start_date AND is_a.event_location = event.event_location JOIN pays ON pays.event_name = event.event_name AND pays.event_start_date = event.event_start_date AND pays.event_location = event.event_location JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN customer ON customer.customer_username = pays.customer_username OR customer.customer_username = is_a.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 -- List of all who can write reviews for a given event
 AND customer.customer_username = $4 AND event.event_active; -- Check if I'm on the list
-- ^^^^^^^ Check if Spectator/Competitors/Organizers (for hosted Events)

-- vvvvvvv Check if your Review
SELECT distinct customer.customer_username FROM review JOIN event ON review.event_name = event.event_name AND review.event_start_date = event.event_start_date AND review.event_location = event.event_location JOIN customer ON customer.customer_username = review.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND review.customer_username = 'ollidab' AND event.event_active;

SELECT distinct customer.customer_username FROM review JOIN event ON review.event_name = event.event_name AND review.event_start_date = event.event_start_date AND review.event_location = event.event_location JOIN customer ON customer.customer_username = review.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND review.customer_username = $5 AND event.event_active;
-- ^^^^^^^ Check if your Review

-- vvvvvvv Check if your Meetup
SELECT distinct customer.customer_username FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location JOIN customer ON customer.customer_username = meetup.customer_username WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND meetup.customer_username = 'ollidab' AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;

SELECT distinct customer.customer_username, event.event_end_date FROM meetup JOIN event ON meetup.event_name = event.event_name AND meetup.event_start_date = event.event_start_date AND meetup.event_location = event.event_location JOIN customer ON customer.customer_username = meetup.customer_username WHERE event.event_name = $1 AND event.event_start_date = $2 AND event.event_location = $3 AND customer.customer_username = $4 AND meetup.customer_username = $5 AND meetup.meetup_start_date = $6 AND meetup.meetup_location = $7 AND event.event_active;
-- ^^^^^^^ Check if your Meetup

 select news_number, news_title, news_content, news_date_posted, bool_and(news_number IN (SELECT news.news_number FROM hosts JOIN event ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username JOIN news ON news.event_name = event.event_name AND news.event_start_date = event.event_start_date AND news.event_location = event.event_location WHERE event.event_name = 'Event 01' AND event.event_start_date = '2015-03-25 09:00:00' AND event.event_location = 'miradero' AND customer.customer_username = 'papaluisre' AND event.event_active)) AS can_edit from news GROUP BY news_number, news_title, news_content, news_date_posted;

SELECT distinct customer.customer_username FROM event LEFT OUTER JOIN hosts ON hosts.event_name = event.event_name AND hosts.event_start_date = event.event_start_date AND hosts.event_location = event.event_location LEFT OUTER JOIN belongs_to ON belongs_to.organization_name = hosts.organization_name JOIN customer ON customer.customer_username = event.customer_username OR customer.customer_username = belongs_to.customer_username WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND event.event_active;

SELECT event.event_name, event.event_start_date, event.event_end_date, event.event_location, event.event_venue, event.event_banner, event.event_logo, event.event_end_date, event.event_registration_deadline, event.event_rules, event.event_description, event.event_deduction_fee, event.event_is_online, event.event_type, bool_and(concat(event.event_name, event.event_location, event.event_start_date) IN (SELECT concat(event.event_name, event.event_location, event.event_start_date) FROM hosts)) as is_hosted FROM event WHERE event.event_name = 'HELLOOOO!!!' AND event.event_start_date = '2015-04-27 22:00:00' AND event.event_location = 'La Serrania' AND event_active GROUP BY event_name, event_start_date, event_location;